<a href="https://colab.research.google.com/github/himanshidalal21-dot/Python/blob/main/LabAssign_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

add = A + B
print("\nAddition (A + B):\n", add)

mul = np.dot(A, B)
print("\nMultiplication (A x B):\n", mul)

Matrix A:
 [[6 1 1]
 [5 7 2]
 [5 4 3]]

Matrix B:
 [[3 5 3]
 [6 2 2]
 [3 1 8]]

Addition (A + B):
 [[ 9  6  4]
 [11  9  4]
 [ 8  5 11]]

Multiplication (A x B):
 [[27 33 28]
 [63 41 45]
 [48 36 47]]


In [4]:
import numpy as np

print("Enter elements for 5x3 matrix:")
A = []
for i in range(5):
    row = list(map(int, input().split()))
    A.append(row)

print("Enter elements for 3x2 matrix:")
B = []
for i in range(3):
    row = list(map(int, input().split()))
    B.append(row)

A = np.array(A)
B = np.array(B)

# Multiply
product = np.dot(A, B)

print("\nProduct Matrix (5x2):\n")
print(product)

Enter elements for 5x3 matrix:
1 2 3
4 5 6 
7 8 9
10 11 12
13 14 15 
Enter elements for 3x2 matrix:
2 3
4 5
6 7

Product Matrix (5x2):

[[ 28  34]
 [ 64  79]
 [100 124]
 [136 169]
 [172 214]]
