<a href="https://colab.research.google.com/github/himanshidalal21-dot/Python/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1 = [11,22,33,44]
array1=np.array(list1)
print(list1)
print(array1)


[11, 22, 33, 44]
[11 22 33 44]


In [ ]:
import numpy as np
list1 = [[11,22,33],[44,55,66]]
array1=np.array(list1)
print(array1)
print(array1.shape)

[[11 22 33]
 [44 55 66]]
(2, 3)


In [ ]:
import numpy as np
list1 = [[11,22,33],[44,55,66],[77,88,99]]
array1=np.array(list1)
print(array1)
print(array1.shape)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
(3, 3)


In [ ]:
import numpy as np
array1 = np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [ ]:
import numpy as np
array1 = np.arange(11,20).reshape(3,3)
print(array1)
print(array1.ndim)
print(array1.shape)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
2
(3, 3)


In [ ]:
import numpy as np
array1 = np.arange(11,29).reshape(2,3,3)
print(array1)
print(array1.ndim)

[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]
3


In [ ]:
import numpy as np
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [ ]:
import numpy as np
array1 = np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])


[20 30]
[20 40 60]
[70 60]
[10 30 50 70]


In [ ]:
import numpy as np
array1 = np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
# print(array1[1,])
# print(array1[:,1])
# print(array1[1:3,1:3])
# print(array1[1:3, ])
# print(array1[: , 1:3])
# print(array1[:1:3])
# print(array1[: , 1:3])
# print(array1[2:4,1])
# print(array1[0,1:3])
# print(array1[0:4,1:3])
print(array1[1,1:3])

[26 27]


In [ ]:
x=np.array([[1,2],
          [3,4]])
y=np.array([[11,12],
          [13,14]])

print(x @ y)
print(y // x)
print(x + y)
print(x - y)
print(x * y)

[[37 40]
 [85 92]]
[[11  6]
 [ 4  3]]
[[12 14]
 [16 18]]
[[-10 -10]
 [-10 -10]]
[[11 24]
 [39 56]]


In [ ]:

import numpy as np
lst = []
n=int(input("Enter number of elements: "))

for i in range(n):
  element = int(input(f"Enter element{i+1}: "))
  lst.append(element)
print("List is: ", lst)
arr = np.array(lst).reshape(3,3)
print("Array:\n",arr)

In [ ]:
for i in range(1,5,2):
  print(i)

1
3


In [ ]:
str1 = "SBJAIN"
for i in range(len(str1)):
  print(i, end="")
print()
for i in range(0,len(str1)):
  print(str1[i], end="")
print()
for i in range(0,len(str1),2):
  print(str1[i], end="")
print()
for i in range(len(str1)-1,-1,-1):
  print(str1[i], end="")

012345
SBJAIN
SJI
NIAJBS

In [ ]:
s1 = 'SBJIAN'
s2 = ' COLLEGE'
if 'I' in s:
  print("Found")
print(s1 + s2)
print('Butter' + 'fly')
print(s * 3)

Found
SBJIAN COLLEGE
Butterfly
SBJIANSBJIANSBJIAN


In [ ]:
s1 = 'SBJAIN COLLEGE'
print(s1[::])
print(s1[::-1])

SBJAIN COLLEGE
EGELLOC NIAJBS


In [ ]:
s='hello'
print(s[:3])
print(s[2:3])
print(s[2:2])
print(s[2:0])
print(s[2::-1])
print(s[2:0:-1])
print(s[9::-1])

hel
l


leh
le
olleh


In [ ]:
s1="Python Programing Language"
print(s1[:])#full string
print(s1[:5])#0,1,2,3,4 Pytho
print(s1[5:10])#5,6,7,8,9 n Pro
print(s1[::-1])#reverse string print
print(s1[5:])#5 position se ene tak
print(s1[:0:-1])#reverse string upto 1 pos
print(s1[100:999])#null output
print(s1[-1:-8:-1])#-1 -2 -3 -4 -5 -6 -7 egaugna
print(s1[5:-1:-1])


Python Programing Language
Pytho
n Pro
egaugnaL gnimargorP nohtyP
n Programing Language
egaugnaL gnimargorP nohty

egaugna



In [ ]:
import numpy as np
p=np.zeros(5)
print(p)

[0. 0. 0. 0. 0.]


In [ ]:
str = "SBJAIN College"
print(len(str))
print(str.capitalize())
print(str.upper())
print(str.isupper())
print(str.lower())
print(str.islower())
print(str.isalpha())
print(str.isalnum())
print(str.isspace())

14
Sbjain college
SBJAIN COLLEGE
False
sbjain college
False
False
False
False


In [ ]:
str = 'SBJain College 54678'
space = 0
digit = 0
alpha = 0
na = 0
for i in str:
  if (i.isspace()):
    space += 1
  if (i.isdigit()):
    digit += 1
  if (i.isalpha()):
    alpha += 1
  if (i.isalnum()):
    na += 1
print("Count Space: ",space)
print("Count Digit: ",digit)
print("Count Alphabet: ",alpha)
print("Count Digit and Alphabet: ",na)

Count Space:  2
Count Digit:  5
Count Alphabet:  13
Count Digit and Alphabet:  18


In [ ]:
s="welcome to python programming"
print(s.find("p"))#find first index  position of p ie: 11
print(s.index("p"))#also same
print(s.find("p",12))#find p from 12 index to end
print(s.index("p",12))#same like find
print(s.find("p",1,13))#find p from 1 to 12 index
print(s.index("p",1,13))#same like find
#difference in both
print(s.find("k"))  #give -1
print(s.index("k")) #give error value error

11
11
18
18
11
11
-1


ValueError: substring not found

In [ ]:
s = "welcome to the python programmimg"
print(s.split(" "))
print(s.partition("y"))
s1 = "     hello"
print(s1)
print(s1.lstrip())
s2 = "hello    "
print(s2)

welcome to the python programmimg
['welcome', 'to', 'the', 'python', 'programmimg']
('welcome to the p', 'y', 'thon programmimg')
     hello
hello
hello    


In [ ]:
#list demo empty list print
my_list1 = []
print(my_list1)
my_list2=list([])
print(my_list2)

[]
[]


In [ ]:
#list to print
my_list1=[1,"hindi",33,44,"edurekha"]
my_list2=list([454,"yogesh","sanjay",55,66,77])
print(my_list1)
print(my_list2)

print(my_list1[:])
print(my_list1[0:3])
print(my_list1[::-1])
print(my_list1[0:5:2])
print(my_list1[1][2])
print(my_list1[-1][1])
print(my_list1 + my_list2)

[1, 'hindi', 33, 44, 'edurekha']
[454, 'yogesh', 'sanjay', 55, 66, 77]
[1, 'hindi', 33, 44, 'edurekha']
[1, 'hindi', 33]
['edurekha', 44, 33, 'hindi', 1]
[1, 33, 'edurekha']
n
d
[1, 'hindi', 33, 44, 'edurekha', 454, 'yogesh', 'sanjay', 55, 66, 77]


In [ ]:
s1 = [10,20,30,40]
s2 = [50,60,70,80]
s1.append([100,101,102])
print(s1)
s2.extend([100,101,102])
print(s2)
s2.insert(-1,'himanshi')
print(s2)
s1.append('Himanshi')
print(s1)

[10, 20, 30, 40, [100, 101, 102]]
[50, 60, 70, 80, 100, 101, 102]
[50, 60, 70, 80, 100, 101, 'himanshi', 102]
[10, 20, 30, 40, [100, 101, 102], 'Himanshi']


In [ ]:
l = [1,2,3,4,5,6,7]
print(l.remove(6))
print(l)
r = [9,8,7,6,5,4]
print(r.clear())
print(r)
x = [10,20,30,40,50]
print(x)
y = x.reverse()
print(x)
print(max(x))

None
[1, 2, 3, 4, 5, 7]
None
[]
[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]
50


In [ ]:
t = tuple('hello')
print(t)

('h', 'e', 'l', 'l', 'o')


In [ ]:
l = ['a','b','c','d','e']
print(l)
t = tuple(l)
print(t)

['a', 'b', 'c', 'd', 'e']
('a', 'b', 'c', 'd', 'e')


In [ ]:
t = tuple(input('Enter data: '))
print(t)

Enter data: HIMANSHI
('H', 'I', 'M', 'A', 'N', 'S', 'H', 'I')


In [ ]:
t1 = (1)
print(1)
t2 = (1,)
print(type(t))

1
<class 'tuple'>


In [ ]:
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)
#nested tuple
t=(1,2,3,(44,55))
print("NESTED TUPLE=>",t)

(1, 2, 3, 4)
(1.2, 1.2, 1.4, 'a')
NESTED TUPLE=> (1, 2, 3, (44, 55))


In [ ]:
t=tuple("HELLO")
print(t)
l=[1,2,3,4,5]
t=tuple(l)
print(t)

('H', 'E', 'L', 'L', 'O')
(1, 2, 3, 4, 5)


In [ ]:
t=(99,88,77,66,55,44,33,22)
print(t[0:5])
print(t[::-1])
print(t[-1:-5:-1])

(99, 88, 77, 66, 55)
(22, 33, 44, 55, 66, 77, 88, 99)
(22, 33, 44, 55)


In [ ]:
l=[1,2,3]
print(tuple(l))
s="python"
print(tuple(s))
d={1:"a",2:"b",3:"c"}
print(tuple(d))
print(tuple(d.values()))

(1, 2, 3)
('p', 'y', 't', 'h', 'o', 'n')
(1, 2, 3)
('a', 'b', 'c')


In [ ]:
t=1,2   #packed
print(t)
x,y=(1,2)  #unpacked
print(x,y)

(1, 2)
1 2


In [ ]:
t=tuple()
totalvalue=int(input("How many element u enter in tuple:"))
for i in range(totalvalue):
    val=int(input("Enter element:"))
    t=t+(val,)
print(t)

How many element u enter in tuple:3
Enter element:21
Enter element:23
Enter element:2005
(21, 23, 2005)


In [ ]:
t = (11,22,33,44,55,66,77)
for i in range(len(t)):
  print(t[i], end=" ")

11 22 33 44 55 66 77 

In [ ]:
t = (24,30,32,34,10,12,14,20,22)
print(t[3:-3])
print(t[-15:7:2])
print(t[1:6:2])
print(t[6:9:2])
print(len(t))
print(max(t))
print(min(t))
print(sorted(t))
print(sum(t))
print(all(t))
print(any(t))

(34, 10, 12)
(24, 32, 10, 14)
(30, 34, 12)
(14, 22)
9
34
10
[10, 12, 14, 20, 22, 24, 30, 32, 34]
198
True
True


In [ ]:
dic={ }  #empty dictionary
print(dic)
print(type(dic))
d=dict()
print(d)
print(type(d))
d={1:"x",2:"y",3:"z"}
print(d)
print(d.keys())
print(d.values())
print(d.items())


{}
<class 'dict'>
{}
<class 'dict'>
{1: 'x', 2: 'y', 3: 'z'}
dict_keys([1, 2, 3])
dict_values(['x', 'y', 'z'])
dict_items([(1, 'x'), (2, 'y'), (3, 'z')])


In [ ]:
d1= {"a":"apple","b":"orange","c":"mango"}
d2=dict(a="apple",b="orange",c="mango")
d3=dict([("a","apple"),("b","orange"),("c","mango")])
d4=dict({"a":"apple","b":"orange","c":"mango"})
print(d1==d2==d3==d4)

True


In [ ]:
d1={1:99,2:67,3:55}
d2={1:99,2:67,3:55}
print(d1==d2)

True


In [ ]:
d={1:"xx",2:"yy",3:"uu"}
print(d[1])#1 indicate key
print(d[3])

xx
uu


In [ ]:
d1=dict()
d1[1]="one"
d1[2]="two"
d1[3]="three"
d1[4]="four"
print(d1)

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
for i in d:
    print(i,end=" ")#keys print
print()
for i in d:
    print(d[i],end=" ")#value of key print
print()
for i in d.values():
    print(i,end=" ")
print()
for i in d:
    print("key=>",i,", value=>",d[i])#value of key print


1 2 3 4 
one two three four 
one two three four 
key=> 1 , value=> one
key=> 2 , value=> two
key=> 3 , value=> three
key=> 4 , value=> four


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d[5] = 'five'
d[1] = 'abc'
print(d)

{1: 'abc', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
print(len(d))
# print(d.clear())
print(d.get(1))
print(d.get(2))

4
one
two


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d.pop(1)#by default last key pair deleted nahi hoti
print(d)
#print(d.pop()) #no argument genertae error


{2: 'two', 3: 'three', 4: 'four'}


In [ ]:
t = (3.14, "hello", 21)
for i in t:
  print(i)

3.14
hello
21


In [ ]:
t1 = (10, 20, 30, 40, 50)
t2 = (60,)
print(t1 + t2)

(10, 20, 30, 40, 50, 60)


In [ ]:
t1 = (10, 20, 30, 40, 50)
s = str(t1)
print(s)

(10, 20, 30, 40, 50)


In [ ]:
t = ("a","b","c","d","e")
print(t[-4])

b
